# 1. Implementing Min-Max Normalization in Python

In [4]:
import pandas as pd
import numpy as np
# Sample data
data = {'Feature1': [1, 2, 3, 4, 5],
        'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)
print(df)
# Min-Max Normalization
normalized_df = (df - df.min()) / (df.max() - df.min())
print(normalized_df)

   Feature1  Feature2
0         1       100
1         2       200
2         3       300
3         4       400
4         5       500
   Feature1  Feature2
0      0.00      0.00
1      0.25      0.25
2      0.50      0.50
3      0.75      0.75
4      1.00      1.00


# 2. Standardization (Z-score Normalization)

In [6]:
# Sample data
data = {'Feature1': [1, 2, 3, 4, 5],
        'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)
# Standardization
standardized_df = (df - df.mean()) / df.std()
print(standardized_df)

   Feature1  Feature2
0 -1.264911 -1.264911
1 -0.632456 -0.632456
2  0.000000  0.000000
3  0.632456  0.632456
4  1.264911  1.264911


# 3. Robust Scaler

In [9]:
from sklearn.preprocessing import RobustScaler

# Sample data
data = {'Feature1': [1, 2, 3, 4, 5],
        'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)
# Robust Scaler
scaler = RobustScaler()
scaled_df = scaler.fit_transform(df)
print(scaled_df)

[[-1.  -1. ]
 [-0.5 -0.5]
 [ 0.   0. ]
 [ 0.5  0.5]
 [ 1.   1. ]]


# 4. MaxAbs Scaler

In [11]:
from sklearn.preprocessing import MaxAbsScaler
# Sample data
data = {'Feature1': [1, 2, 3, 4, 5],
        'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)
# MaxAbs Scaler
scaler = MaxAbsScaler()
maxabs_scaled_df = scaler.fit_transform(df)
print(maxabs_scaled_df)

[[0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]
 [0.8 0.8]
 [1.  1. ]]


# iris dataset

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
file_path1="iris_dataset.csv"
df=pd.read_csv(file_path1)
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0    

# 1. Implementing Min-Max Normalization in Python

In [19]:
columns=["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"] 
df=pd.DataFrame(np.random.rand(20,4),columns=columns)
# Min-Max Normalization
normalized_df = (df - df.min()) / (df.max() - df.min())
print(normalized_df)

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            0.026034          0.127478           1.000000          0.312375
1            0.089156          0.141304           0.784328          0.028008
2            0.983300          0.796947           0.380628          0.884121
3            0.376554          0.798057           0.631112          0.117646
4            0.436064          0.118044           0.474293          0.625799
5            1.000000          0.602405           0.495662          0.396896
6            0.427198          0.943414           0.283565          0.905803
7            0.073366          0.416402           0.559706          0.331456
8            0.507774          0.000000           0.851957          0.827852
9            0.929197          0.332325           0.423712          0.000000
10           0.504895          0.845829           0.000000          0.690780
11           0.587739          0.053635           0.570405          1.000000

# 2. Standardization (Z-score Normalization)

In [19]:
columns=["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"] 
df=pd.DataFrame(np.random.rand(20,4),columns=columns)
# Min-Max Normalization
normalized_df = (df - df.min()) / (df.max() - df.min())
print(normalized_df)

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            0.026034          0.127478           1.000000          0.312375
1            0.089156          0.141304           0.784328          0.028008
2            0.983300          0.796947           0.380628          0.884121
3            0.376554          0.798057           0.631112          0.117646
4            0.436064          0.118044           0.474293          0.625799
5            1.000000          0.602405           0.495662          0.396896
6            0.427198          0.943414           0.283565          0.905803
7            0.073366          0.416402           0.559706          0.331456
8            0.507774          0.000000           0.851957          0.827852
9            0.929197          0.332325           0.423712          0.000000
10           0.504895          0.845829           0.000000          0.690780
11           0.587739          0.053635           0.570405          1.000000

# 3. Robust Scaler

In [21]:
columns=["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"] 
df=pd.DataFrame(np.random.rand(20,4),columns=columns)
scaler = RobustScaler()
scaled_df = scaler.fit_transform(df)
print(scaled_df)

[[-2.81507265e-03  6.56726841e-01 -1.82485136e-01  6.72165796e-01]
 [-4.07727305e-01 -2.49267578e-01  6.51424468e-01 -6.30494741e-01]
 [ 1.48787265e+00  4.20656083e-01  9.96936337e-01 -1.23202358e-03]
 [-1.73332940e+00  2.61936048e-01  3.21018805e-01  5.37289961e-01]
 [-1.93842487e+00  6.61995220e-01 -7.22238969e-02 -1.31160777e-01]
 [-4.05230055e-01 -1.51128321e-01  5.45888244e-01  3.81743397e-01]
 [ 1.50690888e+00  1.03147076e+00  8.69064733e-02 -3.13348762e-01]
 [ 2.81507265e-03 -2.15952045e-01 -3.28916747e-01 -5.81639178e-01]
 [ 2.76146200e-01  8.86412704e-01 -5.11286494e-01  5.71264960e-01]
 [-1.80372454e+00 -4.45547687e-01  5.90425248e-01 -6.22145230e-01]
 [ 8.08518636e-02  9.53921796e-01 -4.50829881e-01  7.23060359e-01]
 [-1.31611195e-01 -3.71800400e-01 -7.15595105e-01  1.23202358e-03]
 [-1.89960778e+00 -5.16914967e-01 -7.21966136e-02  3.07075986e-01]
 [ 6.60801985e-01 -1.95801967e-01  7.27750343e-01 -6.02414627e-01]
 [ 7.06228192e-01  1.51128321e-01 -1.03415652e+00  1.10672089e

# 4. MaxAbs Scaler

In [22]:

columns=["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"] 
df=pd.DataFrame(np.random.rand(20,4),columns=columns)
# MaxAbs Scaler
scaler = MaxAbsScaler()
maxabs_scaled_df = scaler.fit_transform(df)
print(maxabs_scaled_df)

[[0.91554323 0.98302178 1.         0.40061802]
 [0.37020568 0.35776997 0.6908336  0.54305851]
 [0.01107504 1.         0.62077805 1.        ]
 [0.25814898 0.90260922 0.53704403 0.69154701]
 [0.05994998 0.84007081 0.50529927 0.36151243]
 [0.51263494 0.30725816 0.11220078 0.71201326]
 [0.1869675  0.47619854 0.02065813 0.47654563]
 [0.5557029  0.21642936 0.78170679 0.93845752]
 [0.37107683 0.96077208 0.49089394 0.07853316]
 [0.34724886 0.36736263 0.49306398 0.19925624]
 [0.03619592 0.88267456 0.35639068 0.5073116 ]
 [0.22763827 0.29435269 0.66785386 0.64306263]
 [0.08545706 0.89994776 0.09251736 0.85679129]
 [0.32870649 0.5890453  0.89140108 0.12924675]
 [0.63681585 0.70221648 0.75212414 0.27738331]
 [0.49128531 0.83373779 0.70899262 0.65928057]
 [0.39491551 0.43767801 0.81241667 0.2005338 ]
 [0.37148226 0.01647045 0.97133418 0.19253542]
 [1.         0.73300272 0.4390482  0.14372234]
 [0.68687848 0.04919233 0.28514276 0.36107373]]
